registry:
  - name: 'fdiblen-github'
    url: 'https://github.com/fdiblen/plugin-registry'
    branch: 'main'
    plugins:
      - plugins/lower.py
      - plugins/no_decorator.py
logging:
  level: 'DEBUG'
